controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_recipe_delete:
    path: /admin/recettes/delete/{id}
    controller: App\Controller\Admin\RecipeController::delete
    methods: DELETE
